name: Generate and Upload Artifact

on: 
  push:
    branches:
      - master

jobs:
  generate-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run create_txt script  #파일 실행
        run: python create_txt.py

      - name: Upload data.txt as artifact #생성된 .txt파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: data-file #아티팩트 이름
          path: data.txt  #업로드 될 파일

  download-file:
    needs: generate-file  #needs를 통해 순차적인 job 실행
    runs-on: ubuntu-latest

    steps:
      - name: Get Artifact  
        uses: actions/download-artifact@v4  #아티팩트 다운로드
        with:
          name: data-file
      - name: Print data.txt
        run: cat data.txt
